### PR TITLE
Fix R CMD check issue and some deprecation warnings

### LINKED ISSUE #48: Package archived on CRAN
Hi,

As reported in https://github.com/cran-task-views/Epidemiology/issues/65, this package was archived on CRAN a couple of months ago. Is there any plan to resubmit or should the package be removed from the Task View?

I can submit a PR to fix the CRAN check that lead to archival (you might have to fix other issues before resubmitting though).

### PR DESCRIPTION
**Pull request by Bisaloo**
I still see some issues in tests:

> Error in `ggmap::geocode(as.character(the_locations))`: Google now requires an API key; see `ggmap::register_google()`.

But it's `skip_on_cran()` so it shouldn't interfere with CRAN upload

> sf layer has inconsistent datum (+proj=longlat +ellps=WGS84 +no_defs).
Need '+proj=longlat +datum=WGS84'

But it's "just" a warning so it shouldn't interfere with CRAN upload.

Fix #48

### CODE REVIEW

File: R/grid_epiflows.R [hunk 1]
```diff
@@ -16,23 +16,28 @@
...
   ## get_flows returns a 3 column data.frame: from, to, flows (
   input <- get_flows(x)
 
-  ggplot2::ggplot(
-    input, ggplot2::aes_string(y = "from", x = "to")) +
-    ggplot2::geom_point(
-      ggplot2::aes_string(size = "n", color = color_by), ...) +
-    ggplot2::scale_color_discrete(guide = FALSE) +
+  p <- ggplot2::ggplot(
+    input, ggplot2::aes(y = .data$from, x = .data$to)) +
```
Comment (cosi1) [inline R/grid_epiflows.R:28]: Is this necessary? (I'm wondering why we used `aes_string()` instead of plain `aes()` in the first place...)

File: R/print.epiflows.R [hunk 2]
```diff
@@ -23,8 +23,8 @@ print.epiflows <- function(x, ...) {
     cat("\n  // no variables set; use set_vars() to define variables in your locations metadata\n")
   }
   cat("\n  // locations\n\n")
-  print(tibble::as_data_frame(x$linelist))
+  print(tibble::as_tibble(x$linelist))
```
Comment (cosi1) [inline R/print.epiflows.R:26]: This is a potentially breaking change.

**Review by cosi1 — COMMENTED** [review]
Thanks for the PR, @Bisaloo !
Please see the comments.

File: R/grid_epiflows.R (hunk 1 above)
Comment (Bisaloo) [reply R/grid_epiflows.R:28]: I should have provided more context: the last commit fixes some deprecation warnings from tidyverse packages.

In particular, here, `aes_string()` is deprecated and generates a warning: https://ggplot2.tidyverse.org/reference/aes_.html#life-cycle

File: R/print.epiflows.R (hunk 2 above)
Comment (Bisaloo) [reply R/print.epiflows.R:26]: This function is deprecated as well, and `as_tibble()` is the recommended replacement.

https://tibble.tidyverse.org/reference/deprecated.html

File: R/grid_epiflows.R (hunk 1 above)
Comment (cosi1) [reply R/grid_epiflows.R:28]: I see. The package builds successfully after your changes, so I think we can merge it.

Thank you for your contribution!
